In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True,dtype=int) # convert categorical into numerical dataset so that a model can be created

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [6]:
dataset.columns # get the column headers only

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='str')

In [7]:
#Get the independent/Input dataset alone
independent=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]

In [8]:
independent # Display the independant dataset

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [9]:
#Get the dependent/output dataset alone
dependent=dataset[["charges"]]

## Preprocessing for standardization by standardization formula(x-Mean)/Sigma where x is the i/p

In [10]:
# Train the model using the training dataset
import  sklearn.model_selection as GSCV
from sklearn import tree
pram_grid = {'criterion' : ['squared_error', 'absolute_error', 'poisson'],'splitter':['best', 'random'], 'min_samples_split':[2,5,10], 'min_samples_leaf':[2,5,10],'max_features': ['sqrt', 'log2']}
grid = GSCV.GridSearchCV(tree.DecisionTreeRegressor(),pram_grid)
grid.fit(independent,dependent)
re = grid.cv_results_
pd.DataFrame.from_dict(re)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_min_samples_leaf,param_min_samples_split,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.018579,0.024758,0.003403,0.001355,squared_error,sqrt,2,2,best,"{'criterion': 'squared_error', 'max_features':...",0.801909,0.672903,0.430550,0.758903,0.694930,0.671839,0.129037,90
1,0.004602,0.001496,0.003338,0.001401,squared_error,sqrt,2,2,random,"{'criterion': 'squared_error', 'max_features':...",0.686800,0.695653,0.651532,0.775945,0.753424,0.712671,0.045522,76
2,0.005647,0.002829,0.011001,0.009125,squared_error,sqrt,2,5,best,"{'criterion': 'squared_error', 'max_features':...",0.783297,0.581904,0.841652,0.701317,0.786942,0.739022,0.090440,52
3,0.004711,0.001160,0.003014,0.000637,squared_error,sqrt,2,5,random,"{'criterion': 'squared_error', 'max_features':...",0.665289,0.747138,0.770172,0.649966,0.733746,0.713262,0.047146,74
4,0.005316,0.001040,0.002633,0.000719,squared_error,sqrt,2,10,best,"{'criterion': 'squared_error', 'max_features':...",0.809965,0.731243,0.785263,0.784027,0.828423,0.787784,0.032744,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,0.007666,0.004250,0.003153,0.001058,poisson,log2,10,2,random,"{'criterion': 'poisson', 'max_features': 'log2...",0.483657,0.619471,0.707125,0.638704,0.697030,0.629197,0.080051,98
104,0.005726,0.001314,0.003471,0.000662,poisson,log2,10,5,best,"{'criterion': 'poisson', 'max_features': 'log2...",0.863768,0.746460,0.876039,0.652261,0.849926,0.797691,0.086032,9
105,0.003061,0.000970,0.002817,0.000753,poisson,log2,10,5,random,"{'criterion': 'poisson', 'max_features': 'log2...",0.783583,0.684268,0.341723,0.618205,0.710544,0.627665,0.152470,99
106,0.003913,0.000655,0.003398,0.001236,poisson,log2,10,10,best,"{'criterion': 'poisson', 'max_features': 'log2...",0.846806,0.790294,0.830914,0.825500,0.824949,0.823693,0.018476,2
107,0.003626,0.001235,0.002200,0.000979,poisson,log2,10,10,random,"{'criterion': 'poisson', 'max_features': 'log2...",0.732082,0.700586,0.784201,0.675269,0.787950,0.736018,0.044677,56

In [11]:
print("The r2 score value for best parameter {}:".format(grid.best_params_),grid.best_score_)
pred=grid.predict([[32,43.900,2,0,1]])
print(pred) #4449.46200

The r2 score value for best parameter {'criterion': 'absolute_error', 'max_features': 'log2', 'min_samples_leaf': 5, 'min_samples_split': 5, 'splitter': 'best'}: 0.8277537478030379
[43753.33705]

C:\Users\prabha_7589\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(