In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True,dtype=int) # convert categorical into numerical dataset so that a model can be created

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [6]:
dataset.columns # get the column headers only

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='str')

In [7]:
#Get the independent/Input dataset alone
independent=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]

In [8]:
independent # Display the independant dataset

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [9]:
#Get the dependent/output dataset alone
dependent=dataset[["charges"]]

In [10]:
# Train the model using the training dataset
import  sklearn.model_selection as GSCV
from sklearn.ensemble import RandomForestRegressor
param_grid = {'criterion' :['squared_error', 'absolute_error','poisson'],'max_features': ['sqrt', 'log2'],'bootstrap':[True,False],'min_samples_split':[2,5,10], 'min_samples_leaf':[2,5,10],'max_depth':[5,10]}

grid =  GSCV.GridSearchCV(RandomForestRegressor(),param_grid,refit=True,verbose=3,n_jobs=-1)
grid.fit(independent,dependent)
re = grid.cv_results_
pd.DataFrame.from_dict(re)

Fitting 5 folds for each of 216 candidates, totalling 1080 fits

C:\Users\prabha_7589\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_bootstrap,param_criterion,param_max_depth,param_max_features,param_min_samples_leaf,param_min_samples_split,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.441263,0.167692,0.028766,0.009806,True,squared_error,5,sqrt,2,2,"{'bootstrap': True, 'criterion': 'squared_erro...",0.866067,0.805590,0.856147,0.835000,0.854500,0.843461,0.021446,109
1,0.645418,0.115459,0.040269,0.004638,True,squared_error,5,sqrt,2,5,"{'bootstrap': True, 'criterion': 'squared_erro...",0.864520,0.803245,0.867040,0.828929,0.850392,0.842825,0.023975,114
2,0.599833,0.138095,0.035401,0.012881,True,squared_error,5,sqrt,2,10,"{'bootstrap': True, 'criterion': 'squared_erro...",0.865948,0.804843,0.867324,0.836597,0.846026,0.844148,0.022881,100
3,0.592784,0.088322,0.042866,0.013682,True,squared_error,5,sqrt,5,2,"{'bootstrap': True, 'criterion': 'squared_erro...",0.867054,0.803986,0.860085,0.832939,0.852980,0.843409,0.022771,111
4,0.683482,0.120064,0.037092,0.008578,True,squared_error,5,sqrt,5,5,"{'bootstrap': True, 'criterion': 'squared_erro...",0.861076,0.806773,0.854206,0.834943,0.838273,0.839054,0.018837,148
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211,0.627521,0.100027,0.036964,0.006117,False,poisson,10,log2,5,5,"{'bootstrap': False, 'criterion': 'poisson', '...",0.871399,0.797435,0.873023,0.840868,0.854065,0.847358,0.027626,32
212,0.555222,0.059466,0.028026,0.004615,False,poisson,10,log2,5,10,"{'bootstrap': False, 'criterion': 'poisson', '...",0.871682,0.797067,0.871637,0.840479,0.850026,0.846178,0.027415,58
213,0.465725,0.085814,0.039542,0.015747,False,poisson,10,log2,10,2,"{'bootstrap': False, 'criterion': 'poisson', '...",0.874830,0.801383,0.870142,0.836559,0.859813,0.848545,0.027027,10
214,0.525868,0.115483,0.039059,0.005879,False,poisson,10,log2,10,5,"{'bootstrap': False, 'criterion': 'poisson', '...",0.874653,0.799619,0.870864,0.836389,0.855921,0.847489,0.027460,27
215,0.534213,0.057712,0.030144,0.007102,False,poisson,10,log2,10,10,"{'bootstrap': False, 'criterion': 'poisson', '...",0.872129,0.802465,0.863538,0.837613,0.853949,0.845939,0.024573,62

In [11]:

print("The r2 score value for best parameter {}:".format(grid.best_params_),grid.best_score_)
pred=grid.predict([[32,43.900,2,0,1]])
print(pred) #4449.46200

The r2 score value for best parameter {'bootstrap': True, 'criterion': 'squared_error', 'max_depth': 10, 'max_features': 'log2', 'min_samples_leaf': 5, 'min_samples_split': 2}: 0.8505698674763356
[39569.9010263]

C:\Users\prabha_7589\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(